name = "routine-backend"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "routine_main"

[env.dev]
[env.dev.vars]
ENCRYPTION_SECRET = "dev-encryption-secret-key"